llvm: fix build error in libsa hmac code
/usr/src/sys/arch/amd64/stand/boot/../../../../lib/libsa/hmac_sha1.c:30:30: error: argument 'digest' of type 'u_int8_t[20]' (aka 'unsigned char[20]') with mismatched bound [-Werror,-Warray-parameter]
    size_t key_len, u_int8_t digest[SHA1_DIGEST_LENGTH])
                             ^
/usr/src/sys/arch/amd64/stand/boot/../../../../lib/libsa/hmac_sha1.h:25:22: note: previously declared as 'u_int8_t[]' (aka 'unsigned char[]') here
    size_t, u_int8_t []);
                     ^
Pass a pointer instead of an incomplete array in the declaration.