llvm: avoid build error in kernel libz
/usr/src/sys/arch/amd64/stand/boot/../../../../lib/libz/crc32.c:746:23: error: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
unsigned long ZEXPORT crc32_z(crc, buf, len)/usr/src/sys/arch/amd64/stand/boot/../../../../lib/libz/inflate.c:1390:13: error: a function definition without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]
int ZEXPORT inflateEnd(strm)

The definition indeed uses a K&R form, this seems to cause an error even
though the declaration uses ISO.  Work around by disabling
-Wdeprecated-non-prototype.  Other architectures will need an equivalent fixes.

Upstream issue:
https://github.com/madler/zlib/issues/633